# Generated by Django 4.2.7 on 2023-12-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WOD',
            new_name='Workout',
        ),
    ]
