# Generated by Django 5.0 on 2023-12-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossFitTerm_app', '0003_remove_crossfitterm_video_link_crossfitterm_workout_and_more'),
        ('workout_app', '0002_rename_wod_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='exercises',
        ),
        migrations.AddField(
            model_name='workout',
            name='crossfit_terms',
            field=models.ManyToManyField(related_name='workouts', to='crossFitTerm_app.crossfitterm'),
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
