# Generated by Django 4.2.7 on 2023-12-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresspost',
            name='reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
