# Generated by Django 5.0 on 2023-12-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_app', '0003_alter_progresspost_reps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresspost',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
