# Generated by Django 5.0 on 2023-12-16 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress_app', '0010_alter_progresspost_workout_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresspost',
            name='user_id',
        ),
    ]
