# Generated by Django 5.0 on 2023-12-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress_app', '0014_progresspost_workout_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresspost',
            name='workout_description',
        ),
    ]
