# Generated by Django 5.0 on 2023-12-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_app', '0015_remove_progresspost_workout_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresspost',
            name='workout_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
