# Generated by Django 5.0 on 2023-12-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_app', '0017_alter_progresspost_notes_alter_progresspost_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresspost',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progresspost',
            name='reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progresspost',
            name='time_to_complete',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
