# Generated by Django 5.0 on 2023-12-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossFitTerm_app', '0002_remove_crossfitterm_wodfather_tips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crossfitterm',
            name='video_link',
        ),
        migrations.AddField(
            model_name='crossfitterm',
            name='workout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crossfitterm',
            name='term',
            field=models.CharField(max_length=100),
        ),
    ]
